### ISSUE TITLE
Add mssql example

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-demo-apps#5]
Below is a sample Roshni Pattath shared for capturing data from https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp-workload-mssql in a single yaml to ease testing

```
# cat mssql/mssql-pv.yml 
---
kind: Namespace
apiVersion: v1
metadata:
  name: mssql-example
  labels:
    app: mssql

---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: mssql-example
  labels:
    app: mssql
stringData:
  mssql-password: P@ssw0rd1!

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql-example-sa
  namespace: mssql-example
  labels:
    component: mssql-example

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: mssql-example
  labels:
    app: mssql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: mssql-example-scc
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- '*'
users:
- system:admin
- system:serviceaccount:mssql-example:mssql-example-sa

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mssql-deployment
  namespace: mssql-example
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    name: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mssql
        app: mssql
    spec:
      serviceAccountName: mssql-example-sa
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mssql-password
              name: mssql-secret
        image: quay.io/ocpmigrate/mssql-server:latest
        imagePullPolicy: Always
        name: mssql
        securityContext:
          privileged: true
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "3Gi"
            cpu: "2"
          requests:
            memory: "3Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: "/var/opt/mssql/data"
          name: mssql-vol
      volumes:
      - name: mssql-vol
        persistentVolumeClaim:
          claimName: mssql-pvc

---
apiVersion: v1
kind: Service
metadata:
 name: mssql-service
 namespace: mssql-example
spec:
 selector:
   app: mssql
 ports:
   - protocol: TCP
     nodePort: 32001
     port: 1433
     targetPort: 1433
 type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: mssql-app-deployment
 namespace: mssql-example
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: mssql-app
   spec:
     terminationGracePeriodSeconds: 10
     serviceAccountName: mssql-example-sa
     containers:
     - name: mssql-app
       image: quay.io/ocpmigrate/mssql-sample-app:microsoft
       imagePullPolicy: Always
       ports:
       - containerPort: 5000
       securityContext:
         privileged: true
       env:
       - name: ConnString
         value: "Server=mssql-service.mssql-example.svc.cluster.local;Database=ProductCatalog;User ID=WebLogin; password=SQLPass1234!"

---
apiVersion: v1
kind: Service
metadata:
 name: mssql-app-service
 namespace: mssql-example
spec:
 selector:
   app: mssql-app
 ports:
   - name: "tcp"
     protocol: TCP
     port: 5000
     targetPort: 5000

---
apiVersion: v1
kind: Route
metadata:
  name: mssql-app-route
  namespace: mssql-example
spec:
  path: "/"
  to:
    kind: Service
    name: mssql-app-service
```

 # oc get all
NAME                                        READY     STATUS    RESTARTS   AGE
pod/mssql-app-deployment-7fd445c589-5d8r6   1/1       Running   0          15m
pod/mssql-deployment-1-lb4pk                1/1       Running   0          15m

NAME                                       DESIRED   CURRENT   READY     AGE
replicationcontroller/mssql-deployment-1   1         1         1         15m

NAME                        TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/mssql-app-service   ClusterIP      172.25.27.44    <none>        5000/TCP         15m
service/mssql-service       LoadBalancer   172.26.49.131   <pending>     1433:32001/TCP   15m

NAME                                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mssql-app-deployment   1         1         1            1           15m

NAME                                              DESIRED   CURRENT   READY     AGE
replicaset.apps/mssql-app-deployment-7fd445c589   1         1         1         15m

NAME                                                  REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfig.apps.openshift.io/mssql-deployment   1          1         1         config

NAME                                       HOST/PORT                                                    PATH      SERVICES            PORT      TERMINATION   WILDCARD
route.route.openshift.io/mssql-app-route   mssql-app-route-mssql-example.apps.0816-58m.qe.rhcloud.com   /         mssql-app-service   <all>                   None
root@ip-172-31-62-36: ~/go/src/github.com/fusor/mig-demo-apps/apps # oc get all
NAME                                        READY     STATUS    RESTARTS   AGE
pod/mssql-app-deployment-7fd445c589-5d8r6   1/1       Running   0          17m
pod/mssql-deployment-1-lb4pk                1/1       Running   0          17m

NAME                                       DESIRED   CURRENT   READY     AGE
replicationcontroller/mssql-deployment-1   1         1         1         17m

NAME                        TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/mssql-app-service   ClusterIP      172.25.27.44    <none>        5000/TCP         17m
service/mssql-service       LoadBalancer   172.26.49.131   <pending>     1433:32001/TCP   17m

NAME                                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mssql-app-deployment   1         1         1            1           17m

NAME                                              DESIRED   CURRENT   READY     AGE
replicaset.apps/mssql-app-deployment-7fd445c589   1         1         1         17m

NAME                                                  REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfig.apps.openshift.io/mssql-deployment   1          1         1         config
